#!/bin/sh

packageid="craw"
buildpath=$(pwd)

if [[ -e "$buildpath/pkg/$packageid" ]];then
    rm "$buildpath/pkg/$packageid"
fi

shc -f "$buildpath/src/$packageid" -o "$buildpath/pkg/$packageid"

cd "$buildpath/pkg/"

tar c $packageid | xz > "package.tar.xz" &&

if [[ -e "$buildpath/dist/package.tar.xz" ]];then
    rm "$buildpath/dist/package.tar.xz"
fi

mv -f "package.tar.xz" "$buildpath/dist/"

cd .. 

git add .
git commit -m "update $(date)"
git push
