#!/bin/bash


## CRAW KEY LUKS DRIVE ENCRYPTION
## development by null
## copyright@2025 PT LEKTOR MEDIA UTAMA


clear
echo "-------------------------------------------------"
echo " Craw Vault Management"
echo " development by null@2025"
echo "-------------------------------------------------"


cgetgrup=$( sudo lvs | grep "ring" | awk $'{ print $2 }')
clvparse="/dev/$cgetgrup/ring"


function craw_open_ring_device() {

    echo " OPENING : Insert vault password"
    echo "-------------------------------------------------"
    sudo cryptsetup luksOpen $clvparse lvm_ring

    if [[ ! -d "$HOME/.ssh"  ]];then
        sudo mkdir -p "$HOME/.ssh"
        sudo chmod 700 "$HOME/.ssh"
    fi
    sudo mount /dev/mapper/lvm_ring "$HOME/.ssh"
}


function craw_close_ring_device() {

    echo " CLOSING : decrypt vault device"
    echo "-------------------------------------------------"

    mountar=$(lsblk | grep "$HOME/.ssh")
    mountsc="/dev/mapper/lvm_ring"

    if [[ ! -z $mounted ]] || [[ -e $mountsc ]];then
        cd ~ && sudo umount -R "$HOME/.ssh"
        sudo cryptsetup luksClose /dev/mapper/lvm_ring
    fi
}


if [[ -e $clvparse ]];then
    if [[ ! -e /dev/mapper/lvm_ring ]];then
        craw_open_ring_device
    else
        craw_close_ring_device
    fi
fi